const fs=require('fs');const path=require('path');const R=path.resolve(__dirname,'../../../../../');global.window=global;
const {PluginHarness,ext}=require('../../../../test/helpers/plugin-harness.cjs');
eval(fs.readFileSync(path.join(R,'web-player', 'src/js', 'compiler.js'),'utf8'));
eval(fs.readFileSync(path.join(R,'web-player', 'src/js', 'instrument-library.js'),'utf8'));
function check(x,m){if(!x)throw new Error(m);}function peak(a){let p=0;for(const x of a)p=Math.max(p,Math.abs(x));return p;}function rms(a){let s=0;for(const x of a)s+=x*x;return Math.sqrt(s/Math.max(1,a.length));}
// A1: ChannelStrip = parametric EQ + dynamics + M/S width/balance in one Plugin.
const cs=new PluginHarness(R,'plugins/effects/channel-strip/plugin.wasm');const cd=cs.descriptor,cx=ext(cd);check(cd.id==='soraoto.channel-strip','channel-strip id');check((cd.parameters||[]).length===19,'channel-strip parameter count');for(const n of ['hpf_freq','low_gain','mid_gain','high_gain','lpf_freq','comp_threshold','comp_ratio','width','balance'])check(cd.parameters.some(p=>p.path===n),`channel-strip missing ${n}`);const csp=new Set((cd.factory_presets||[]).map(x=>x.meta?.name));for(const n of ['lead','bass','guitar','keys','pad','drums','mix_bus'])check(csp.has(n),`channel-strip preset ${n}`);
const N=128,inputL=Float32Array.from({length:N},(_,i)=>Math.sin(i*.17)*.35),inputR=Float32Array.from({length:N},(_,i)=>Math.sin(i*.19)*.31);cs.applyPreset('lead');const co=cs.process(N,{inputs:[[inputL,inputR]]})[0];check(peak(co[0])>.001&&peak(co[1])>.001,'channel-strip silent');check(co[0].every(Number.isFinite)&&co[1].every(Number.isFinite),'channel-strip nonfinite');cs.close();
// A2/A3: per-voice modulation + standardized note expressions are actually rendered.
function cleanSynth(){const h=new PluginHarness(R,'plugins/dsp/super-synth/plugin.wasm');for(const [k,v] of Object.entries({master_gain:.65,voice_gain:.8,osc_a_position:0,osc_b_level:0,sub_level:0,noise_level:0,unison_voices:1,unison_detune:0,stereo_spread:0,amp_attack:.001,amp_decay:.002,amp_sustain:1,amp_release:.08,filter_cutoff:19000,filter_resonance:0,filter_drive:0,filter_env_amount:0,velocity_to_filter:0,pressure_to_filter:0,timbre_to_position:0,lfo1_pitch:0,lfo1_cutoff:0,lfo2_position:0,chorus_mix:0,saturation:0,output_width:1,engine_model:'wavetable',voice_drift:0,voice_lfo_spread:0,voice_age_motion:0,voice_timbre_spread:0,voice_pan_spread:0}))h.setPlain(k,v);return h;}
function renderExpr(expr){const h=cleanSynth(),L=[],Rr=[];for(let b=0;b<80;b++){const events=[];if(b===0){events.push({kind:1,noteId:1,pitch:69,velocity:.8,offset:0});if(expr)events.push({kind:3,noteId:1,expressionId:expr.id,value:expr.value,offset:0});}const o=h.process(128,{events})[0];L.push(...o[0]);Rr.push(...o[1]);}h.close();return [L,Rr];}
const base=renderExpr(null),quiet=renderExpr({id:4,value:.2}),right=renderExpr({id:5,value:1});check(rms(quiet[0])<rms(base[0])*.55,'volume expression not applied independently of velocity');check(rms(right[1])>rms(right[0])*1.35,'pan expression not applied');
const sh=new PluginHarness(R,'plugins/dsp/super-synth/plugin.wasm'),sd=sh.descriptor;sh.close();check(sd.version==='8.0.0','SuperSynth v8 revision');check((sd.parameters||[]).length===157,'SuperSynth v8 parameter count');for(const n of ['voice_age_motion','voice_timbre_spread','voice_pan_spread'])check(sd.parameters.some(p=>p.path===n),`missing per-voice parameter ${n}`);check((sd.note_expressions||[]).map(x=>x.id).join(',')==='1,2,3,4,5','note expression ABI ids');
// A4: compiler output + arrangement automation coverage in every non-Chopin public sample.
const catalog=JSON.parse(fs.readFileSync(path.join(R,'web-player', 'public/songs','index.json'),'utf8')).songs.filter(x=>x.category!=='Chopin');let noteExpressions=0,tracks=0;
for(const song of catalog){const src=fs.readFileSync(path.join(R,'web-player', 'public/songs',song.file),'utf8'),ir=SoraotoCompiler.compile(src),errors=(ir.diagnostics||[]).filter(x=>x.kind==='error');check(!errors.length,`${song.id}: compile errors ${JSON.stringify(errors)}`);const lead=ir.tracks.find(t=>t.name==='Lead');check(lead,`${song.id}: Lead missing`);for(const t of ir.tracks){tracks++;check((t.effects||[]).some(f=>f.name==='ChannelStrip'),`${song.id}/${t.name}: ChannelStrip missing`);for(const e of t.events||[])if(e.type==='note'){check(e.performance?.compiler==='instrument-performance-v2',`${song.id}/${t.name}: performance compiler missing`);check(Array.isArray(e.noteExpressions),`${song.id}/${t.name}: expression list missing`);noteExpressions+=e.noteExpressions.length;}}
 const targets=new Set((lead.timelineAutomation||[]).map(x=>x.target));for(const t of ['instrument.filter_cutoff','stereo.width','send.Space','effects.ChannelStrip.mid_gain'])check(targets.has(t),`${song.id}: arrangement automation ${t} missing`);for(const a of lead.timelineAutomation||[])check((a.points||[]).length>=ir.structure.length,`${song.id}: sparse automation ${a.target}`);
}
const ag=fs.readFileSync(path.join(R,'web-player', 'src/js', 'audio-graph.js'),'utf8'),app=fs.readFileSync(path.join(R,'web-player', 'src/js', 'app.js'),'utf8');for(const token of ['target.startsWith("instrument.")','target==="stereo.width"','target.startsWith("send.")','setNamedParameter?.(m[2],value,at)'])check(ag.includes(token),`audio graph missing ${token}`);check(app.includes('node.noteExpression?.(id,Number(x.id),Number(x.value),at)'),'scheduler does not emit per-note expressions');check(app.includes('{...perfTrack,gain:expressionAt(track,event.time),pan:0}'),'fallback pan is still double-applied');
console.log('PASS priority-A audio',{channelStripParams:cd.parameters.length,superSynthParams:sd.parameters.length,publicSongs:catalog.length,tracks,noteExpressions,volumeExpressionRatio:+(rms(quiet[0])/rms(base[0])).toFixed(3),panRatio:+(rms(right[1])/Math.max(1e-9,rms(right[0]))).toFixed(3)});
