const path=require('path');const R=path.resolve(__dirname,'../../../../../');const {PluginHarness,ext}=require('../../../../test/helpers/plugin-harness.cjs');
function check(x,m){if(!x)throw new Error(m);}function peak(a){let p=0;for(const x of a)p=Math.max(p,Math.abs(x));return p;}function rms(a){let s=0;for(const x of a)s+=x*x;return Math.sqrt(s/Math.max(1,a.length));}
// Reverb presets must produce a deterministic audible tail.
for(const preset of ['room','plate','hall','chamber','ambience']){const h=new PluginHarness(R,'plugins/effects/reverb/plugin.wasm');h.applyPreset(preset);let late=0;for(let b=0;b<220;b++){const x=new Float32Array(128);if(!b)x[0]=.5;const o=h.process(128,{inputs:[[x,x]]})[0];if(b>24)late=Math.max(late,peak(o[0]),peak(o[1]));}check(late>.00001,`${preset}: no reverb tail`);h.close();}
// True-peak limiter must have lookahead and constrain a deliberately hot signal.
{const h=new PluginHarness(R,'plugins/effects/master-limiter/plugin.wasm');h.setPlain('ceiling',-1);check(h.e.soraoto_plugin_latency_samples()>=48,'limiter latency missing');let pk=0;for(let b=0;b<100;b++){const x=Float32Array.from({length:128},(_,i)=>i%2?2.4:-2.4);const o=h.process(128,{inputs:[[x,x]]})[0];pk=Math.max(pk,peak(o[0]),peak(o[1]));}check(pk<=.9,`true peak limiter overshoot ${pk}`);h.close();}
// Drum kit must render the standard lanes as distinct, non-silent voices.
{const levels={};for(const [name,pitch] of Object.entries({kick:36,snare:38,hat:42,openHat:46,tom:47,ride:51,crash:49,rim:37})){const h=new PluginHarness(R,'plugins/dsp/drum-machine/plugin.wasm');h.applyPreset('studio');let all=[];for(let b=0;b<90;b++){const ev=b===0?[{kind:1,noteId:1,pitch,velocity:.9,offset:0}]:[];all.push(...h.process(128,{events:ev})[0][0]);}levels[name]=rms(all);check(levels[name]>.0003,`${name}: silent`);h.close();}check(new Set(Object.values(levels).map(x=>x.toFixed(4))).size>=5,'drum voices insufficiently distinct');}
// Current SuperSynth production presets must exercise each supported engine model.
{const h=new PluginHarness(R,'plugins/dsp/super-synth/plugin.wasm'),programs=h.descriptor.program_lists?.[0]?.programs||[];h.close();const models=new Set(programs.map(p=>p.attributes?.['soraoto.engine']||'wavetable'));for(const model of ['wavetable','pluck','tine','piano','concert_grand','bowed','flute','reed','brass','vocal'])check(models.has(model),`missing synth model ${model}`);}
const fs=require('fs');const catalog=JSON.parse(fs.readFileSync(path.join(R,'web-player', 'public/songs','index.json'),'utf8'));let spatialSongs=0;for(const song of catalog.songs){if(song.category==='Chopin')continue;const src=fs.readFileSync(path.join(R,'web-player', 'public/songs',song.file),'utf8');check(src.includes('bus Space {')&&src.includes('Reverb {')&&src.includes('Space -> Master'),`${song.id}: shared reverb bus missing`);spatialSongs++;}
console.log('PASS priority-S audio',{reverbPresets:5,limiterLookahead:true,drumPlugin:true,superSynthModels:6,spatialSongs});
