const fs=require('fs');const path=require('path');const {PluginHarness}=require('../../../../test/helpers/plugin-harness.cjs');
const R=path.resolve(__dirname,'../../../../../'),FILE='plugins/dsp/super-synth/plugin.wasm';
function check(x,m){if(!x)throw new Error(m);}function rms(a,s,e){let q=0,n=0;for(let i=s;i<Math.min(e,a.length);i++){q+=a[i]*a[i];n++;}return Math.sqrt(q/Math.max(1,n));}
function render(name,{velocity=.8,pitch=60,pressureAt=-1,overrides={}}={}){const h=new PluginHarness(R,FILE,{sampleRate:48000,maxFrames:128});h.applyPreset(name);for(const [k,v] of Object.entries(overrides))h.setPlain(k,v);const N=96000,out=[];for(let frame=0;frame<N;frame+=128){const ev=[];if(frame===0)ev.push({kind:1,noteId:1,pitch,velocity,offset:0});if(pressureAt>=0&&frame<=pressureAt&&frame+128>pressureAt)ev.push({kind:3,noteId:1,expressionId:2,value:.95,offset:pressureAt-frame});const o=h.process(128,{events:ev})[0];for(const ch of o)for(const x of ch)check(Number.isFinite(x),`${name}: non-finite`);out.push(...o[0]);}h.close();return Float64Array.from(out.slice(0,N));}
const guitar=render('clean_guitar'),gEarly=rms(guitar,0,7200),gLate=rms(guitar,36000,48000);check(gEarly>gLate*3,`pluck decay missing ${gEarly}/${gLate}`);
const pLo=render('soft_piano',{velocity:.25}),pHi=render('soft_piano',{velocity:.9}),pLoE=rms(pLo,0,7200),pHiE=rms(pHi,0,7200);check(pHiE>pLoE*2.5,`hammer velocity response weak ${pLoE}/${pHiE}`);
const strings=render('strings_wide'),sEarly=rms(strings,0,7200),sLate=rms(strings,36000,48000);check(sLate>sEarly*.9,`bowed sustain collapsed ${sEarly}/${sLate}`);
const fluteLow=render('flute_air',{overrides:{flute_breath_pressure:.25}}),fluteHigh=render('flute_air',{overrides:{flute_breath_pressure:.90}}),fLow=rms(fluteLow,12000,40000),fHigh=rms(fluteHigh,12000,40000);check(fHigh>fLow*1.20,`flute breath response weak ${fLow}/${fHigh}`);
// Extreme TPT-SVF conditions must remain finite and preserve a stereo image.
const h=new PluginHarness(R,FILE,{sampleRate:48000,maxFrames:128});h.applyPreset('supersaw_lead');for(const [k,v] of [['oversample','x4'],['filter_resonance',.96],['filter_drive',1],['filter_cutoff',17000],['filter_mode','lowpass'],['unison_voices',8],['stereo_spread',1],['output_width',1.5],['chorus_mix',0]])h.setPlain(k,v);let eM=0,eS=0,pk=0;for(let b=0;b<180;b++){const ev=b===0?[{kind:1,noteId:1,pitch:72,velocity:.9,offset:0}]:[];const o=h.process(128,{events:ev})[0];for(let i=0;i<o[0].length;i++){const L=o[0][i],Rr=o[1][i];check(Number.isFinite(L)&&Number.isFinite(Rr),'TPT filter non-finite');pk=Math.max(pk,Math.abs(L),Math.abs(Rr));const m=(L+Rr)*.5,s=(L-Rr)*.5;eM+=m*m;eS+=s*s;}}h.close();check(pk<1.2,`TPT unsafe peak ${pk}`);check(eS>eM*.001,`stereo image collapsed through filter ${eS}/${eM}`);
console.log('PASS SuperSynth v7 core quality',{guitarDecay:+(gEarly/gLate).toFixed(2),pianoVelocity:+(pHiE/pLoE).toFixed(2),bowedSustain:+(sLate/sEarly).toFixed(2),fluteBreath:+(fHigh/fLow).toFixed(2),tptPeak:+pk.toFixed(4),stereoSideRatio:+(eS/eM).toFixed(4)});
