const fs=require('fs');const path=require('path');const R=path.resolve(__dirname,'../../../../../');const {PluginHarness}=require('../../../../test/helpers/plugin-harness.cjs');
function check(x,m){if(!x)throw new Error(m);}const FILE='plugins/dsp/super-synth/plugin.wasm';
function setCleanSine(h){const p={master_gain:.55,voice_gain:.75,osc_a_position:0,osc_b_level:0,sub_level:0,noise_level:0,unison_voices:1,unison_detune:0,stereo_spread:0,fm_amount:0,ring_mix:0,amp_attack:.001,amp_decay:.002,amp_sustain:1,amp_release:.08,filter_cutoff:19000,filter_resonance:0,filter_drive:0,filter_mode:'lowpass',filter_env_amount:0,keytrack:0,velocity_to_filter:0,pressure_to_filter:0,timbre_to_position:0,lfo1_pitch:0,lfo1_cutoff:0,lfo2_position:0,chorus_mix:0,saturation:0,osc_a_warp:0,osc_b_warp:0,output_width:1,engine_model:'wavetable',voice_drift:0,voice_lfo_spread:0};for(const [n,v] of Object.entries(p))h.setPlain(n,v);}
function renderPitch(pitch,seconds=.8,expression=null){const h=new PluginHarness(R,FILE);setCleanSine(h);const n=128,blocks=Math.ceil(seconds*48000/n),samples=[];for(let b=0;b<blocks;b++){const events=[];if(b===0)events.push({kind:1,noteId:1,pitch,velocity:.8,offset:0});if(expression&&b===expression.block)events.push({kind:3,noteId:1,expressionId:expression.id,value:expression.value,offset:0});const o=h.process(n,{events})[0][0];samples.push(...o);}h.close();return samples;}
function estimateHz(samples,sr=48000,startSec=.18,endSec=null){const a=Math.floor(startSec*sr),z=endSec==null?samples.length:Math.min(samples.length,Math.floor(endSec*sr));let prev=samples[a],crossings=[];for(let i=a+1;i<z;i++){const x=samples[i];if(prev<=0&&x>0)crossings.push(i);prev=x;}if(crossings.length<12)throw new Error('too few crossings');let total=0;for(let i=1;i<crossings.length;i++)total+=crossings[i]-crossings[i-1];return sr/(total/(crossings.length-1));}
const a4=estimateHz(renderPitch(69)),a4half=estimateHz(renderPitch(69.5));check(Math.abs(a4-440)<5,`A4 ${a4}`);check(Math.abs(a4half-452.89)<6,`A4+50c ${a4half}`);check(a4half>a4+7,'fractional pitch rounded');
const bent=renderPitch(69,.9,{block:150,id:1,value:12}),before=estimateHz(bent,48000,.18,.35),after=estimateHz(bent,48000,.55,.82);check(Math.abs(before-440)<6,`base pitch ${before}`);check(Math.abs(after-880)<18,`pitch expression ${after}`);
const src=fs.readFileSync(path.join(R,'wasm','plugins','dsp','super-synth','src','plugin.c'),'utf8');for(const feature of ['WT_FRAMES','WT_MIPS','MAX_UNISON','wt_lookup','mip_for_freq','tpt_filter_step','chorus','engine==1','voice_lfo1'])check(src.toLowerCase().includes(feature.toLowerCase()),`missing synth feature ${feature}`);check(src.includes('g_wt[WT_FRAMES][WT_MIPS][WT_SIZE]'),'mipmapped wavetable bank missing');
console.log('PASS synth v7 wavetable quality',{a4Hz:a4.toFixed(2),a4Plus50cHz:a4half.toFixed(2),pitchExpressionHz:after.toFixed(2),pluginAbi:'1.0'});
