const fs=require('fs');const path=require('path');global.window=global;const R=path.resolve(__dirname,'..'),REPOSITORY_ROOT=path.resolve(R,'..'),WASM_ROOT=path.join(REPOSITORY_ROOT,'wasm');
const {wasmPath}=require('../../wasm/test/helpers/plugin-harness.cjs');
const html=fs.readFileSync(path.join(R,'index.html'),'utf8'),app=fs.readFileSync(path.join(R,'src/js/app.js'),'utf8'),host=fs.readFileSync(path.join(R,'src/js/plugin-host.js'),'utf8');
function check(x,m){if(!x)throw new Error(m);}
const m=html.match(/window\.SORAOTO_BUILD_ID="([^"]+)"/);check(m,'build ID missing');const BUILD=m[1];
for(const f of ['compiler.js','midi-export.js','wav-export.js','plugin-cbor.js','plugin-interface.js','plugin-host.js','plugin-registry.js','audio-graph.js','instrument-library.js','app.js'])check(html.includes(`${f}?v=${BUILD}`),`cache-busted script missing: ${f}`);
check(html.indexOf('js/plugin-cbor.js')<html.indexOf('js/plugin-interface.js'),'CBOR must load before interface validator');check(html.indexOf('js/plugin-interface.js')<html.indexOf('js/plugin-host.js'),'interface validator must load before plugin host');check(html.indexOf('js/plugin-host.js')<html.indexOf('js/plugin-registry.js'),'plugin host must load before registry');check(html.indexOf('js/plugin-registry.js')<html.indexOf('js/audio-graph.js'),'plugin registry must load before graph');check(html.indexOf('js/instrument-library.js')<html.indexOf('js/app.js'),'instrument library before app');
check(app.includes('function assertAudioRuntime()')&&app.includes('SoraotoPluginHost?.createInstrument'),'Plugin runtime assertion missing');check(host.includes('assets/worklets/soraoto-plugin-processor.js?v='),'Plugin worklet cache bust missing');check(host.includes('soraoto.plugin.v1'),'descriptor section missing');check(host.includes('Legacy Plugin ABI export is forbidden'),'legacy export rejection missing');
const plugins=[['effects','gain'],['effects','stereo-delay'],['effects','channel-strip'],['effects','sidechain'],['effects','reverb'],['effects','master-limiter'],['dsp','drum-machine'],['dsp','super-synth']];
for(const [group,name] of plugins){const relative=path.join('plugins',group,name,'plugin.wasm'),bytes=fs.readFileSync(wasmPath(REPOSITORY_ROOT,relative)),mod=new WebAssembly.Module(bytes),secs=WebAssembly.Module.customSections(mod,'soraoto.plugin.v1');if(name==='super-synth')check(WebAssembly.Module.customSections(mod,'soraoto.interface').length===1,'SuperSynth v6 soraoto.interface missing');check(secs.length===1,`${name}: descriptor section`);const names=new Set(WebAssembly.Module.exports(mod).map(x=>x.name));for(const k of ['soraoto_plugin_abi_version','soraoto_plugin_init','soraoto_plugin_control','soraoto_plugin_activate','soraoto_plugin_start_processing','soraoto_plugin_process'])check(names.has(k),`${name}: missing ${k}`);for(const k of ['init','set_parameter','note_on','process'])check(!names.has(k),`${name}: legacy export ${k}`);check(fs.existsSync(path.join(WASM_ROOT,'plugins',group,name,'src','plugin.c')),`${name}: source layout`);}
check(fs.existsSync(path.join(WASM_ROOT,'shared','plugin_abi_runtime.h')),'shared ABI runtime missing');check(fs.existsSync(path.join(REPOSITORY_ROOT,'build','wasm','generated')),'CMake generated descriptor dir missing');
check(!fs.readdirSync(WASM_ROOT).some(x=>x.endsWith('.manifest.json')),'external plugin manifest remains');
console.log('PASS publication audit',{build:BUILD,pluginAbi:'1.0',plugins:plugins.length,cleanPluginLayout:true,externalManifests:false});
