const fs=require('fs'),path=require('path');global.window=global;
const R=path.resolve(__dirname,'../..');
const {PluginHarness}=require('./helpers/plugin-harness.cjs');
eval(fs.readFileSync(path.join(R,'web-player/src/js/compiler.js'),'utf8'));
eval(fs.readFileSync(path.join(R,'web-player/src/js/instrument-library.js'),'utf8'));
function check(x,m){if(!x)throw new Error(m);}
const SR=16000,BLOCK=128,BEATS_PER_SECTION=4;
function db(x){return 20*Math.log10(Math.max(1e-12,x));}
function percentile(a,p){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),i=Math.min(b.length-1,Math.max(0,Math.floor((b.length-1)*p)));return b[i];}
function onePoleLow(x,cut,sr){const a=1-Math.exp(-2*Math.PI*cut/sr),o=new Float64Array(x.length);let y=0;for(let i=0;i<x.length;i++){y+=a*(x[i]-y);o[i]=y;}return o;}
function rms(x){let s=0;for(const v of x)s+=v*v;return Math.sqrt(s/Math.max(1,x.length));}
function kWeight(x,sr){ // deterministic BS.1770-style approximation valid across CI sample rates
  function biquad(type,f,Q,gainDb,input){const A=Math.pow(10,gainDb/40),w=2*Math.PI*f/sr,c=Math.cos(w),sn=Math.sin(w),alpha=sn/(2*Q);let b0,b1,b2,a0,a1,a2;
    if(type==='hp'){b0=(1+c)/2;b1=-(1+c);b2=(1+c)/2;a0=1+alpha;a1=-2*c;a2=1-alpha;}
    else {const S=1,al=sn/2*Math.sqrt((A+1/A)*(1/S-1)+2),sq=2*Math.sqrt(A)*al;b0=A*((A+1)+(A-1)*c+sq);b1=-2*A*((A-1)+(A+1)*c);b2=A*((A+1)+(A-1)*c-sq);a0=(A+1)-(A-1)*c+sq;a1=2*((A-1)-(A+1)*c);a2=(A+1)-(A-1)*c-sq;}
    b0/=a0;b1/=a0;b2/=a0;a1/=a0;a2/=a0;const out=new Float64Array(input.length);let x1=0,x2=0,y1=0,y2=0;for(let i=0;i<input.length;i++){const xi=input[i],y=b0*xi+b1*x1+b2*x2-a1*y1-a2*y2;out[i]=y;x2=x1;x1=xi;y2=y1;y1=y;}return out;}
  return biquad('hp',38,0.5,0,biquad('shelf',1681,0.707,4,x));
}
function integratedLufs(L,R){const l=kWeight(L,SR),r=kWeight(R,SR),win=Math.max(1,Math.round(.4*SR)),hop=Math.max(1,Math.round(.1*SR)),blocks=[];for(let s=0;s+win<=l.length;s+=hop){let e=0;for(let i=s;i<s+win;i++)e+=l[i]*l[i]+r[i]*r[i];e/=win;blocks.push({e,l:-.691+10*Math.log10(Math.max(1e-15,e))});}let use=blocks.filter(x=>x.l>-70);if(!use.length)return -Infinity;let mean=use.reduce((a,x)=>a+x.e,0)/use.length,pre=-.691+10*Math.log10(mean),gate=pre-10;use=use.filter(x=>x.l>gate);mean=use.reduce((a,x)=>a+x.e,0)/Math.max(1,use.length);return -.691+10*Math.log10(Math.max(1e-15,mean));}
function truePeak(x){let p=0;for(let i=0;i<x.length;i++)p=Math.max(p,Math.abs(x[i]));for(let i=1;i<x.length-2;i++){const p0=x[i-1],p1=x[i],p2=x[i+1],p3=x[i+2];for(let k=1;k<4;k++){const t=k/4,t2=t*t,t3=t2*t;const v=.5*((2*p1)+(-p0+p2)*t+(2*p0-5*p1+4*p2-p3)*t2+(-p0+3*p1-3*p2+p3)*t3);p=Math.max(p,Math.abs(v));}}return p;}
function metrics(L,R,sectionLufs){let meanL=0,meanR=0,eL=0,eR=0,cross=0;for(let i=0;i<L.length;i++){meanL+=L[i];meanR+=R[i];eL+=L[i]*L[i];eR+=R[i]*R[i];cross+=L[i]*R[i];}meanL/=L.length;meanR/=R.length;eL/=L.length;eR/=R.length;cross/=L.length;const total=Math.sqrt((eL+eR)/2),tp=Math.max(truePeak(L),truePeak(R));const lowL=onePoleLow(L,180,SR),lowR=onePoleLow(R,180,SR),low=(rms(lowL)**2+rms(lowR)**2)/Math.max(1e-12,eL+eR);const lp3L=onePoleLow(L,3000,SR),lp3R=onePoleLow(R,3000,SR);let he=0;for(let i=0;i<L.length;i++){const a=L[i]-lp3L[i],b=R[i]-lp3R[i];he+=a*a+b*b;}he/=L.length;const high=he/Math.max(1e-12,eL+eR);const corr=cross/Math.sqrt(Math.max(1e-15,eL*eR));const wins=[],w=Math.max(1,Math.round(.1*SR));for(let s=0;s+w<=L.length;s+=w){let e=0;for(let i=s;i<s+w;i++)e+=(L[i]*L[i]+R[i]*R[i])/2;wins.push(10*Math.log10(Math.max(1e-12,e/w)));}const dyn=percentile(wins,.95)-percentile(wins,.20),imb=Math.abs(10*Math.log10(Math.max(1e-12,eL)/Math.max(1e-12,eR)));return {lufs:integratedLufs(L,R),truePeakDb:db(tp),crestDb:db(tp/Math.max(1e-12,total)),dc:Math.max(Math.abs(meanL),Math.abs(meanR)),lowRatio:low,highRatio:high,correlation:corr,dynamicRangeDb:dyn,stereoImbalanceDb:imb,sectionDiffDb:Math.max(...sectionLufs)-Math.min(...sectionLufs)};}
function addPan(mixL,mixR,l,r,gain,pan){const a=(pan+1)*Math.PI/4,gl=Math.cos(a)*Math.SQRT2,gr=Math.sin(a)*Math.SQRT2;for(let i=0;i<l.length;i++){mixL[i]+=l[i]*gain*gl;mixR[i]+=(r[i]??l[i])*gain*gr;}}
function renderTrack(track,startBeat,endBeat,tempo){const spb=60/tempo,frames=Math.ceil((endBeat-startBeat)*spb*SR),hasDrum=(track.events||[]).some(e=>e.type==='drum'),hasNote=(track.events||[]).some(e=>e.type==='note');if(!hasDrum&&!hasNote)return [new Float64Array(frames),new Float64Array(frames)];const file=hasDrum?'plugins/dsp/drum-machine/plugin.wasm':'plugins/dsp/super-synth/plugin.wasm',h=new PluginHarness(R,file,{sampleRate:SR,maxFrames:BLOCK});if(hasDrum)h.applyPreset(window.SoraotoInstruments.drumPresetFor(track));else {const preset=window.SoraotoInstruments.superSynthPresetFor(track);if(preset)h.applyPreset(preset);}const q=[];let nid=1;for(const e of track.events||[]){if(e.time<startBeat||e.time>=endBeat)continue;const on=Math.round((e.time-startBeat)*spb*SR);if(e.type==='drum'){q.push({frame:on,ev:{kind:1,noteId:nid++,pitch:window.SoraotoInstruments.drumPitchFor(e),velocity:e.velocity??.75}});continue;}for(const pitch of e.pitches||[]){const id=nid++;q.push({frame:on,ev:{kind:1,noteId:id,pitch,velocity:e.velocity??.7}});const off=Math.round((e.time+e.duration-startBeat)*spb*SR);if(off<frames)q.push({frame:off,ev:{kind:2,noteId:id,pitch,velocity:0}});for(const x of e.noteExpressions||[]){const f=Math.round((e.time+x.offset-startBeat)*spb*SR);if(f>=0&&f<frames)q.push({frame:f,ev:{kind:3,noteId:id,expressionId:x.id,value:x.value}});}}}q.sort((a,b)=>a.frame-b.frame);const L=new Float64Array(frames),RR=new Float64Array(frames);let qi=0;for(let f=0;f<frames;f+=BLOCK){const n=Math.min(BLOCK,frames-f),ev=[];while(qi<q.length&&q[qi].frame<f+n){if(q[qi].frame>=f)ev.push({...q[qi].ev,offset:q[qi].frame-f});qi++;}const o=h.process(n,{events:ev})[0];L.set(o[0],f);RR.set(o[1],f);}h.close();return [L,RR];}
function limit(L,R){const h=new PluginHarness(Root,'plugins/effects/master-limiter/plugin.wasm',{sampleRate:SR,maxFrames:BLOCK});}
const Root=R;
function renderSection(ir,sc){const end=Math.min(sc.endBeat,sc.startBeat+BEATS_PER_SECTION),frames=Math.ceil((end-sc.startBeat)*(60/ir.tempo)*SR),L=new Float64Array(frames),RR=new Float64Array(frames);for(const t of ir.tracks){const [l,r]=renderTrack(t,sc.startBeat,end,ir.tempo);addPan(L,RR,l,r,t.gain??1,t.pan??0);} // master limiter is part of final safety path
  const h=new PluginHarness(R,'plugins/effects/master-limiter/plugin.wasm',{sampleRate:SR,maxFrames:BLOCK}),oL=new Float64Array(frames),oR=new Float64Array(frames);for(let f=0;f<frames;f+=BLOCK){const n=Math.min(BLOCK,frames-f),a=Float32Array.from(L.subarray(f,f+n)),b=Float32Array.from(RR.subarray(f,f+n)),o=h.process(n,{inputs:[[a,b]]})[0];oL.set(o[0],f);oR.set(o[1],f);}h.close();return [oL,oR];}
const ids=['jpop-blue-hour-signal','anime-starforge-opening','game-crimson-phase','field-wind-over-lumeria','techno-midnight-grid','jazz-blue-lantern'];
const catalog=JSON.parse(fs.readFileSync(path.join(R,'web-player/public/songs/index.json'),'utf8')).songs;const report={};
for(const id of ids){const meta=catalog.find(x=>x.id===id),ir=SoraotoCompiler.compile(fs.readFileSync(path.join(R,'web-player', 'public/songs',meta.file),'utf8'));check(!(ir.diagnostics||[]).some(x=>x.kind==='error'),`${id}: compile`);const chunks=[],sectionLufs=[];for(const sc of ir.structure){const [L,Rr]=renderSection(ir,sc);chunks.push([L,Rr]);sectionLufs.push(integratedLufs(L,Rr));}const len=chunks.reduce((n,x)=>n+x[0].length,0),L=new Float64Array(len),RR=new Float64Array(len);let at=0;for(const [l,r] of chunks){L.set(l,at);RR.set(r,at);at+=l.length;}const m=metrics(L,RR,sectionLufs);for(const [k,v] of Object.entries(m))check(Number.isFinite(v),`${id}: ${k} nonfinite`);check(m.lufs>-45&&m.lufs<-3,`${id}: loudness ${m.lufs}`);check(m.truePeakDb<-0.2&&m.truePeakDb>-30,`${id}: true peak ${m.truePeakDb}`);check(m.crestDb>1&&m.crestDb<30,`${id}: crest ${m.crestDb}`);check(m.dc<0.03,`${id}: DC ${m.dc}`);check(m.lowRatio>=0&&m.lowRatio<0.85,`${id}: LF ratio ${m.lowRatio}`);check(m.highRatio>=0&&m.highRatio<0.9,`${id}: spectral high ratio ${m.highRatio}`);check(m.correlation>=-1.001&&m.correlation<=1.001,`${id}: stereo correlation ${m.correlation}`);check(m.stereoImbalanceDb<9,`${id}: stereo imbalance ${m.stereoImbalanceDb}`);check(m.dynamicRangeDb>.2&&m.dynamicRangeDb<50,`${id}: dynamic range ${m.dynamicRangeDb}`);check(m.sectionDiffDb>.15&&m.sectionDiffDb<30,`${id}: section loudness difference ${m.sectionDiffDb}`);report[id]=Object.fromEntries(Object.entries(m).map(([k,v])=>[k,+v.toFixed(3)]));console.log('PASS audio quality',id,report[id]);}
console.log('PASS audio quality regression',{sampleRate:SR,representatives:ids.length,metrics:['Integrated LUFS','True Peak','crest factor','DC','low-frequency energy','spectral balance','stereo correlation','dynamic range','section loudness difference']});
