const fs=require('fs');const path=require('path');const R=path.resolve(__dirname,'../..');global.window=global;
const {PluginHarness,ext}=require('./helpers/plugin-harness.cjs');
eval(fs.readFileSync(path.join(R,'web-player', 'src/js', 'compiler.js'),'utf8'));
eval(fs.readFileSync(path.join(R,'web-player', 'src/js', 'instrument-library.js'),'utf8'));
function check(x,m){if(!x)throw new Error(m);}function peak2(o){let p=0;for(const ch of o)for(const x of ch)p=Math.max(p,Math.abs(x));return p;}
const catalog=JSON.parse(fs.readFileSync(path.join(R,'web-player', 'public/songs','index.json'),'utf8')).songs.filter(x=>x.category!=='Chopin');
const synthProbe=new PluginHarness(R,'plugins/dsp/super-synth/plugin.wasm'),synthPresets=new Set((synthProbe.descriptor.factory_presets||[]).map(x=>x.meta?.name));synthProbe.close();
const drumProbe=new PluginHarness(R,'plugins/dsp/drum-machine/plugin.wasm'),drumPresets=new Set((drumProbe.descriptor.factory_presets||[]).map(x=>x.meta?.name));drumProbe.close();
const usedSynth=new Set(),usedDrums=new Set();let eventCount=0,pannedTracks=0;
function pathToMaster(graph,start){const seen=new Set();const q=[start];while(q.length){const n=q.shift();if(n==='Master')return true;if(seen.has(n))continue;seen.add(n);for(const e of graph.edges||[])if(e.from===n)q.push(e.to);}return false;}
for(const song of catalog){const src=fs.readFileSync(path.join(R,'web-player', 'public/songs',song.file),'utf8'),ir=SoraotoCompiler.compile(src),errors=(ir.diagnostics||[]).filter(d=>d.kind==='error');check(!errors.length,`${song.id}: compile error`);check(ir.length>0&&Number.isFinite(ir.length),`${song.id}: invalid length`);for(const t of ir.tracks){check(pathToMaster(ir.audioGraph,t.name),`${song.id}/${t.name}: no route to Master`);check(Number.isFinite(t.gain)&&t.gain>0&&t.gain<=2,`${song.id}/${t.name}: bad gain ${t.gain}`);check(Number.isFinite(t.pan)&&t.pan>=-1&&t.pan<=1,`${song.id}/${t.name}: bad pan ${t.pan}`);if(Math.abs(t.pan)>.001)pannedTracks++;for(const c of t.controls||[])if(c.type==='automation'&&['gain','volume'].includes(String(c.target).toLowerCase()))check(Number.isFinite(c.value)&&c.value>0&&c.value<=2,`${song.id}/${t.name}: bad gain automation`);eventCount+=(t.events||[]).length;
 const notes=(t.events||[]).filter(e=>e.type==='note'),drums=(t.events||[]).filter(e=>e.type==='drum');if(notes.length){let preset=t.instrumentDescriptor?.params?.preset?.value||null;if(!preset)preset=window.SoraotoInstruments.superSynthPresetFor(t);check(preset&&synthPresets.has(preset),`${song.id}/${t.name}: unresolved synth preset ${preset}`);usedSynth.add(preset);check(notes.some(e=>(e.noteExpressions||[]).length>0),`${song.id}/${t.name}: performance expressions absent`);}if(drums.length){const preset=window.SoraotoInstruments.drumPresetFor(t);check(drumPresets.has(preset),`${song.id}/${t.name}: unresolved drum preset ${preset}`);usedDrums.add(preset);for(const e of drums.slice(0,16))check(Number.isFinite(window.SoraotoInstruments.drumPitchFor(e)),`${song.id}/${t.name}: unmapped drum ${e.drum}`);}}
 for(const e of ir.audioGraph.edges||[])check(Number.isFinite(e.gain)&&e.gain>=0&&e.gain<=4,`${song.id}: bad route gain ${e.from}->${e.to}`);
}
// Render every timbre actually used by the public non-Chopin catalog.
for(const preset of usedSynth){const h=new PluginHarness(R,'plugins/dsp/super-synth/plugin.wasm');h.applyPreset(preset);let p=0;for(let b=0;b<80;b++){const ev=b===0?[{kind:1,noteId:1,pitch:60,velocity:.8,offset:0}]:[];p=Math.max(p,peak2(h.process(128,{events:ev})[0]));}h.close();check(p>.00001,`synth preset ${preset} silent`);}
for(const preset of usedDrums){const h=new PluginHarness(R,'plugins/dsp/drum-machine/plugin.wasm');h.applyPreset(preset);let p=0;for(const pitch of [36,38,42,46,49,51]){const o=h.process(128,{events:[{kind:1,noteId:pitch,pitch,velocity:.8,offset:0}]})[0];p=Math.max(p,peak2(o));for(let b=0;b<8;b++)p=Math.max(p,peak2(h.process(128,{})[0]));}h.close();check(p>.0008,`drum preset ${preset} silent`);}
const ag=fs.readFileSync(path.join(R,'web-player', 'src/js', 'audio-graph.js'),'utf8');check(ag.includes('createStereoStage(ctx,Math.max(-1,Math.min(1,basePan+'),'track pan not applied at graph stage');check(ag.includes('prepareTimelineAutomation'),'timeline automation not prepared');
console.log('PASS non-Chopin playback',{songs:catalog.length,events:eventCount,pannedTracks,synthPresets:[...usedSynth].sort(),drumPresets:[...usedDrums].sort()});
